; This file is for the FamiTone2 library and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : NES Game Song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $70 ; 00 : Bass
	.word @env4, @env2, @env3
	.byte $00
	.byte $30 ; 01 : Drums
	.word @env0, @env1, @env1
	.byte $00
	.byte $70 ; 02 : Lead Synth
	.word @env4, @env1, @env3
	.byte $00

@env0:
	.byte $ca,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $bf,$c0,$00,$01
@env3:
	.byte $c6,$be,$bd,$be,$c1,$c0,$00,$05
@env4:
	.byte $cb,$cd,$cf,$00,$02

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $cf, $84
@song0ref15:
	.byte $3a, $9b, $00, $9b, $48, $9b, $00, $9b, $3a, $9b, $00, $9b, $44, $9b, $00, $87, $42, $91, $3e, $9b, $00, $87, $3a, $91
	.byte $3e, $9b, $00, $9b, $42, $9b, $00, $9b, $3a, $9b, $00, $c3, $30, $91, $3a, $91, $89, $00, $c3, $30, $91, $2c, $9b, $00
	.byte $87, $2a, $91, $2c, $9b, $00, $87, $30, $91, $3e, $9b, $00, $c3, $cf
	.byte $ff, $24
	.word @song0ref15
@song0ref80:
	.byte $48, $91, $3a, $91, $00, $cd, $4c, $91, $48, $9b, $00, $87, $44, $91, $42, $9b, $00, $87, $44, $91, $48, $9b, $00, $c3
	.byte $cf
	.byte $ff, $3e
	.word @song0ref15
	.byte $ff, $24
	.word @song0ref15
	.byte $ff, $19
	.word @song0ref80
	.byte $ff, $3e
	.word @song0ref15
	.byte $ff, $24
	.word @song0ref15
	.byte $ff, $19
	.word @song0ref80
	.byte $ff, $3e
	.word @song0ref15
	.byte $ff, $24
	.word @song0ref15
	.byte $ff, $18
	.word @song0ref80
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref136:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $f9, $f9, $cb, $cf, $84
@song0ref165:
	.byte $52, $9b, $00, $9b, $60, $9b, $00, $9b, $52, $9b, $00, $9b, $5c, $9b, $00, $87, $5a, $91, $56, $9b, $00, $87, $52, $91
	.byte $56, $9b, $00, $9b, $5a, $9b, $00, $9b, $52, $9b, $00, $c3, $48, $91, $52, $91, $89, $00, $c3, $48, $91, $44, $9b, $00
	.byte $87, $42, $91, $44, $9b, $00, $87, $48, $91, $56, $9b, $00, $c3, $cf
	.byte $ff, $24
	.word @song0ref165
@song0ref230:
	.byte $60, $91, $52, $91, $89, $00, $c3, $64, $91, $60, $9b, $00, $87, $5c, $91, $5a, $9b, $00, $87, $5c, $91, $60, $9b, $00
	.byte $c3, $cf
	.byte $ff, $3e
	.word @song0ref165
	.byte $ff, $24
	.word @song0ref165
	.byte $60, $91, $52, $91, $00, $cd, $64, $91, $60, $9b, $00, $87, $5c, $91, $5a, $9b, $00, $87, $5c, $91, $60, $9b, $00, $c3
	.byte $cf
	.byte $ff, $3e
	.word @song0ref165
	.byte $ff, $24
	.word @song0ref165
	.byte $ff, $19
	.word @song0ref230
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $2c, $91, $22, $a5, $22, $91, $00, $a5, $22, $91, $22
@song0ref312:
	.byte $a5
@song0ref313:
	.byte $22, $91, $00, $a5, $22, $91, $2c, $a5, $2c, $91, $00, $a5, $2c, $91, $2c, $a5, $2c, $91, $00, $a5, $2c, $91, $22, $a5
	.byte $22, $91, $00, $a5, $22, $91, $22, $91, $93
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $1f
	.word @song0ref313
	.byte $ff, $22
	.word @song0ref312
	.byte $ff, $14
	.word @song0ref313
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $cf, $82
@song0ref403:
	.byte $5c, $87, $00, $d7, $5e, $87, $00, $87, $5c, $87, $00, $eb, $5a, $87, $00, $d7, $5c, $87, $00, $87, $5a, $87, $00, $eb
	.byte $5c, $87, $00, $c3, $93, $5e, $87, $00, $87, $5c, $87, $00, $eb, $5a, $87, $00, $d7, $5c, $87, $00, $87, $5a, $87, $00
	.byte $9b, $cf
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $32
	.word @song0ref403
	.byte $ff, $31
	.word @song0ref403
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $1b
	.word @song0ref136
	.byte $ff, $1b
	.word @song0ref136
	.byte $ff, $1b
	.word @song0ref136
	.byte $fd
	.word @song0ch4loop
